// Test scaffolding, not application code.
//
// The app pulls exclusively from USDA FoodData Central and no longer speaks to
// Open Food Facts. The saved responses in fixtures/off_products/ are still the
// best corpus of real-world category vocabulary we have - 33 products whose tags
// were written by hand by contributors rather than generated by our own mapper -
// and the classification engine still consumes exactly that vocabulary, so the
// corpus keeps testing the engine even though nothing fetches it any more.
//
// This is the mapper the app used to carry, kept here so those fixtures can be
// replayed. It is eval-ed on top of the engine slice, so the helpers it calls
// (tagsLookLikeBeverage, looksArtificiallySweetened) resolve as globals.
const OFF_FIELDS = "code,product_name,brands,serving_size,serving_quantity,nutriments,categories_tags,nutrition_data_per,ingredients_text,ingredients,additives_tags";
function foodFromOFF(p) {
  const n = p.nutriments || {};
  const g = (k) => { const v = n[k]; return (typeof v === "number") ? v : (v != null && v !== "" ? parseFloat(v) : null); };
  const cats = (p.categories_tags || []).map(c => String(c).toLowerCase());
  const isBeverage = tagsLookLikeBeverage(cats);
  const per100 = {
    kcal: g("energy-kcal_100g"), fat: g("fat_100g"), sat: g("saturated-fat_100g"),
    sugars: g("sugars_100g"), added: g("added-sugars_100g"), protein: g("proteins_100g"),
  };
  let serv = {
    kcal: g("energy-kcal_serving"), fat: g("fat_serving"), sat: g("saturated-fat_serving"),
    sugars: g("sugars_serving"), added: g("added-sugars_serving"), protein: g("proteins_serving"),
  };
  const servQty = (typeof p.serving_quantity === "number") ? p.serving_quantity : parseFloat(p.serving_quantity);
  if (serv.kcal == null && per100.kcal != null && servQty > 0) {
    const f = servQty / 100;
    serv = { kcal: per100.kcal * f, fat: nz(per100.fat, f), sat: nz(per100.sat, f), sugars: nz(per100.sugars, f), added: nz(per100.added, f), protein: nz(per100.protein, f) };
  }
  let servingLabel = p.serving_size || (servQty > 0 ? servQty + " g" : "100 g");
  servingLabel = servingLabel.replace(/(\([^()]*\))(\s*\1)+/g, "$1"); // collapse duplicated "(28 g) (28 g)"
  const base = (serv.kcal != null) ? serv : per100;
  const baseLabel = (serv.kcal != null) ? ("per serving (" + servingLabel + ")") : "per 100 g";
  return {
    name: p.product_name || "Unnamed product", brand: p.brands || "",
    cats, isBeverage, per100, serv, base, baseLabel, servingLabel,
    servQtyG: servQty > 0 ? servQty : null,
    ingredients: (p.ingredients || []).map(i => ({ text: i.text, pct: (typeof i.percent === "number" ? i.percent : i.percent_estimate) })),
    sweetened: looksArtificiallySweetened(p.ingredients_text, p.additives_tags),
    source: "Open Food Facts", code: p.code || "",
  };
  function nz(v, f) { return v == null ? null : v * f; }
}
